/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as association from "./Association";
export type { association };
import type * as campaign from "./Campaign";
export type { campaign };
import type * as dao from "./DAO";
export type { dao };
import type * as plateformSol from "./Plateform.sol";
export type { plateformSol };
