/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as associationSol from "./Association.sol";
export type { associationSol };
import type * as campaign from "./Campaign";
export type { campaign };
export type { AssociationFactory } from "./AssociationFactory";
