/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as associationSol from "./Association.sol";
export type { associationSol };
export type { AssociationFactory } from "./AssociationFactory";
export * as factories from "./factories";
export type { AssociationContract } from "./Association.sol/AssociationContract";
export { AssociationContract__factory } from "./factories/Association.sol/AssociationContract__factory";
export { AssociationFactory__factory } from "./factories/AssociationFactory__factory";
